### ISSUE TITLE
harvesting scripts

### ISSUE THREAD

**Issue by timlinux** [jgrocha/covid-pt#1]
Hi @jgrocha 

Thanks so much for sharing this! Could you include the scripts that you use to generate the gpkges too? I'd like to try to make some visualisations using the new WMS-T stuff we did.

**Comment by jgrocha** [comment]
Hi @timlinux 

I've published a few scripts. To get the data out of the PDF, I use the `relatorio.py` script. Check the `Readme.md` on the `Relatórios` folder. The data goes to a local Postgresql database.

Afterwards, I use QGIS (what else?) to generate the geopackage (using the processing in PyQGIS) and the maps. I do all PyQGIS in just one script `2geopackage.py`, on the `geopackage` folder.

There are more detailed instructions on the Readme.md files, but probably not enough. I'll close this issue for now.

**Comment by timlinux** [comment]
Ah brilliant thank you so much!
